Fix bug in caps lock light logic.
zsa/qmk_firmware pull request #341
Opened 2021-08-09 18:44 UTC by Xaeroxe

When the caps lock LED was first implemented it used layer 1's LED. This is no longer true, so this condition needs to be updated as caps lock is now using an LED for layer 3 and 6.

2021-08-09 21:42 UTC, Xaeroxe commented
I'm happy to rebase this onto firmware_21 if that would be more helpful.

2021-10-28 06:28 UTC, Xaeroxe commented
Seems like this merges cleanly into firmware21, so it is now targeting that.

2021-11-03 16:03 UTC, blueyed commented
How does it relate to https://github.com/zsa/qmk_firmware/pull/335?

2021-11-03 16:09 UTC, Xaeroxe commented
@blueyed #335 contains similar fixes to this one, however this PR resolves a race condition to make the lights on the keyboard flicker less and be more predictable. Also that PR introduces a compile time constant which allows you to use the caps lock LED exclusively for caps lock, rather than sharing it with the layer functionality.

2021-12-07 16:47 UTC, drashna commented
Firmware 21 would probably be the better target. 

But as with #335, I think that it may be better to simple use LED 6 for caps lock exclusively, when it's enabled.

2021-12-07 20:16 UTC, Xaeroxe commented
@drashna addressed in 2655f0d

2021-12-07 20:29 UTC, Xaeroxe commented
Woops, missed one, got it in 772a9d1

2021-12-07 22:49 UTC, drashna requested changes
And add: 
```c
#ifdef CAPS_LOCK_STATUS
bool led_update_kb(led_t led_state) {
    bool res = led_update_user(led_state);
    if(res) {
        ML_LED_6(led_state.caps_lock);
    }
    return res;
}
#endif
```

2021-12-07 22:49 UTC, drashna commented on keyboards/moonlander/moonlander.c
> +#if !defined(MOONLANDER_USER_LEDS) && defined(CAPS_LOCK_STATUS)
```suggestion
#if !defined(MOONLANDER_USER_LEDS)
```

2021-12-07 22:49 UTC, drashna commented on keyboards/moonlander/moonlander.c
> +#endif
```suggestion
```

2021-12-08 03:36 UTC, Xaeroxe commented
@drashna addressed in b86bfe6

2021-12-11 18:45 UTC, drashna commented on keyboards/moonlander/moonlander.c
> +    ML_LED_6(LED_6);
```suggestion
#if !defined(CAPS_LOCK_STATUS)
    ML_LED_6(LED_6);
#endif
```

2021-12-28 02:36 UTC, merged